### ISSUE TITLE
C# bindings for CGAL

### ISSUE THREAD

**Issue by VE-2016** [CGAL/cgal-swig-bindings#101] opened 2018-05-20 12:15 UTC
My question is about binding CGAL to C# library. Is this type of binding possible and any method of this conversion would be very appreciated.

Best regards,
JK

**Comment by DaveInCaz** [comment] 2020-12-07 13:53
This seems to be a duplicate of https://github.com/CGAL/cgal-swig-bindings/issues/3

**Closed** 2020-12-07 13:58 UTC
Labels: duplicate
