### ISSUE TITLE
 DLL load failed while importing _CGAL_Polygon_mesh_processing

### ISSUE THREAD

**Issue by Greyscaler** [CGAL/cgal-swig-bindings#253] opened 2023-11-15 09:09 UTC
DLL load failed while importing _CGAL_Polygon_mesh_processing
![Screenshot 2023-11-15 105830](https://github.com/CGAL/cgal-swig-bindings/assets/83281013/74409d0a-c24a-4d93-8c3f-ba9094d328bc)

I'm using Windows 11, Python 3.10.11 and I got an error while importing CGAL_Polygon_mesh_processing module. I double checked _CGAL_Polygon_mesh_processing.pyd does exist in the CGAL folder. I did try to use WMware with Ubuntu and importing of Polygon mesh processing module went fine. Probably it's somehow connected with dependencies on Windows.

---

Edit: 

Important comment: https://github.com/CGAL/cgal-swig-bindings/issues/253#issuecomment-1833381412

**Comment by lrineau** [comment] 2023-11-15 15:16
How have you install the CGAL Python bindings?

Can you please show the result of the following command?

```
python -m pip show cgal
```

**Comment by Greyscaler** [comment] 2023-11-15 15:58
Sure, here:
![Screenshot 2023-11-15 175455](https://github.com/CGAL/cgal-swig-bindings/assets/83281013/e4822c5b-df79-4128-963b-1fc1d62b5f24)
I used "python -m pip install cgal" command for installation

**Comment by Greyscaler** [comment] 2023-11-28 20:33
Originally my goal is to install cgal module inside blender python
So after I added all dll directories, I got this error:
![Screenshot 2023-11-28 221828](https://github.com/CGAL/cgal-swig-bindings/assets/83281013/9e2ccc80-ea2e-4d94-909e-87efa82a57c0)
"**The specified procedure could not be found**."

I did manage to resolve this issue by swapping tbb12.dll, tbbmalloc.dll and tbbmalloc_proxy.dll. I got them from Intel OneAPI TBB, I used version 2021.11. Now library imports just fine, basically it was a problem with bundled tbb dll

**Comment by Greyscaler** [comment] 2023-11-28 20:47
I found it by rebuilding the whole solution.
There was a problem with tbb. I added env variable TBB_ROOT 
![image](https://github.com/CGAL/cgal-swig-bindings/assets/83281013/ffe99afd-01e9-49b9-a057-7ea63e08c145)
By doing this linker managed to find the library, but it didn't resolve an issue. What was left is for each project switch useOneTBB parameter to "yes".
![Screenshot 2023-11-28 223816](https://github.com/CGAL/cgal-swig-bindings/assets/83281013/802dabe7-f941-4d5f-abbe-f7229ed80818)
So after that build compiled just fine.

**Comment by lrineau** [comment] 2023-11-30 09:16
I am surprised of those results. Our wheels are tested by the CI process.

... well, maybe that is because they are tested on the same Github worker that builds the wheels. The dependencies are already in the system.

**Comment by lrineau** [comment] 2023-11-30 09:20
> I am surprised of those results. Our wheels are tested by the CI process.
> 
> ... well, maybe that is because they are tested on the same Github worker that builds the wheels. The dependencies are already in the system.

@SaillantNicolas can you check if one can modify the workflow so that this "step" is extracted to a different "job"

https://github.com/CGAL/cgal-swig-bindings/blob/3c9fe115c4c864b884e35ee65679a659ab77fce8/.github/workflows/tests.yml#L183C23-L183C28

That job would install Python, download and install the artifact, and then test the wheel, without installing any other dependency.

**Comment by NahomKidane** [comment] 2023-12-18 19:58
I have the same issue when trying to import alpha_wrap_3  (from CGAL.CGAL_Alpha_wrap_3 import alpha_wrap_3).  This after using pip install cgal.  Any solution?



ImportError: DLL load failed while importing _CGAL_Alpha_wrap_3: The specified module could not be found.

**Comment by Greyscaler** [comment] 2023-12-18 20:36
> I have the same issue when trying to import alpha_wrap_3 (from CGAL.CGAL_Alpha_wrap_3 import alpha_wrap_3). This after using pip install cgal. Any solution?
> 
> ImportError: DLL load failed while importing _CGAL_Alpha_wrap_3: The specified module could not be found.

Try to install intel oneAPI TBB, then copy tbb12.dll from C:\Program Files (x86)\Intel\oneAPI\tbb\latest\bin to cgal directory in site-packages

**Comment by sloriot** [comment] 2023-12-19 07:54
Alpha wrap is not part of the alpha shape package. There is currently no bindings for alpha wrap.

**Comment by lrineau** [comment] 2023-12-19 14:06
> Alpha wrap is not part of the alpha shape package. There is currently no bindings for alpha wrap.

@sloriot, you have added alpha wrap in commit ca5f0c4e6cb191a94658559bd2e55451bf7ae1db.

**Comment by sloriot** [comment] 2023-12-19 14:27
Indeed! Thanks for the reminder. Then check this example:https://github.com/CGAL/cgal-swig-bindings/commit/ca5f0c4e6cb191a94658559bd2e55451bf7ae1db#diff-1563bde9d4cc8726902b54b11506f91b6dff70062fb0f0e66c89f418a8265f3f

**Comment by NahomKidane** [comment] 2023-12-19 14:33
> > I have the same issue when trying to import alpha_wrap_3 (from CGAL.CGAL_Alpha_wrap_3 import alpha_wrap_3). This after using pip install cgal. Any solution?
> > ImportError: DLL load failed while importing _CGAL_Alpha_wrap_3: The specified module could not be found.
> 
> Try to install intel oneAPI TBB, then copy tbb12.dll from C:\Program Files (x86)\Intel\oneAPI\tbb\latest\bin to cgal directory in site-packages

Thank you @Greyscaler! This fixed the issue.

**Comment by lrineau** [comment] 2024-01-25 13:19
We (CGAL project) are working on the issue, and our Github Actions can now reproduce the issue. For example: https://github.com/CGAL/cgal-swig-bindings/actions/runs/7654331055/job/20860050398#step:5:36

We will work on the resolution of that issue, now.

**Comment by lrineau** [comment] 2024-04-25 07:51
That issue was fixed by the PR https://github.com/CGAL/cgal-swig-bindings/pull/262.

See now for example the automatic builds and tests, at https://github.com/CGAL/cgal-swig-bindings/actions/runs/8769446360.

**Closed by lrineau** 2024-04-25 07:51 UTC
